#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: code from coffee

# Short bio or description (displayed in the header)
description: live.in.mind

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  # email: codefromcoffee@gmail.com
  facebook:
  flickr:
  github: lizardspoc
  instagram:
  linkedin: geerhardtvandeventer
  pinterest:
  rss: cfc# just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: codefromcoffee
  stackoverflow: users/5297153/lizardspoc # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: codefromcoffee

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-69827404-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
# url: http://lizardspoc.github.io
url: http://www.codefromcoffee.net

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# markdown: redcarpet
highlighter: pygments

permalink: /

# The release of Jekyll Now that you're using
version: v1.1.0

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

paginate: 3
#paginate_path: "/archive/page:num/"

excerpt_separator: "READ"
